### ISSUE TITLE
Contribution Details

### ISSUE THREAD

**Issue by greatdaveo** [OpenSource-GH/dumsor-tracker-frontend#3]
Hi bosses, please, can we have the contribution guidelines? Thanks.

**Comment by topboyasante** [comment]
sure!

**Comment by topboyasante** [comment]
@Elvis020 :
- Create a contribution folder
- Add the markdown for contributions
- Link it to the main readme

**Comment by greatdaveo** [comment]
> @Elvis020 :
> 
> * Create a contribution folder
> * Add the markdown for contributions
> * Link it to the main readme

Chief! Please can I do this now?

**Comment by topboyasante** [comment]
sure!

**Comment by greatdaveo** [comment]
> @greatdaveo The link in the main readme.md is not routing to the contributions file

Sorry, I have fixed that. Thanks.
