### ISSUE TITLE
Authentication with Email and Password

### ISSUE THREAD

**Issue by topboyasante** [OpenSource-GH/dumsor-tracker-frontend#32]
We need to connect the frontend to the backend. We'll start with the authentication.
- Implement authentication with email and password. the route to the backend is : `api.dumsor.xyz/api/v1/users/login`.
- The structure of the data is as follows:
`{
email:"",
password:""
}`

**Comment by Salladin95** [comment]
hey, can anybody assign it to me?

**Comment by topboyasante** [comment]
hi @Salladin95 . sure!
i'm making changes to the route you'd use, but yeah you can pick it up.

**Comment by topboyasante** [comment]
@Salladin95 you can proceed.

**Comment by Salladin95** [comment]
@topboyasante Are you sure that API is working correctly? I was testing it with Postman, and after creating a user at "api.dumsor.xyz/api/v1/users/signup" I couldn't login.

I get such a response:

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Error</title>
</head>

<body>
    <pre>Error: Failed to log in user<br> &nbsp; &nbsp;at exports.login (/opt/render/project/src/controllers/authController.js:49:17)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/opt/render/project/src/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/opt/render/project/src/node_modules/express/lib/router/route.js:149:13)<br> &nbsp; &nbsp;at Route.dispatch (/opt/render/project/src/node_modules/express/lib/router/route.js:119:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/opt/render/project/src/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /opt/render/project/src/node_modules/express/lib/router/index.js:284:15<br> &nbsp; &nbsp;at Function.process_params (/opt/render/project/src/node_modules/express/lib/router/index.js:346:12)<br> &nbsp; &nbsp;at next (/opt/render/project/src/node_modules/express/lib/router/index.js:280:10)<br> &nbsp; &nbsp;at Function.handle (/opt/render/project/src/node_modules/express/lib/router/index.js:175:3)<br> &nbsp; &nbsp;at router (/opt/render/project/src/node_modules/express/lib/router/index.js:47:12)</pre>
</body>

</html>

**Comment by topboyasante** [comment]
hi @Salladin95. it's an issue on the BE. i'll get it fixed. you can carry on though.

**Comment by Salladin95** [comment]
@topboyasante hey, how do you want to handle successfull call to API? When it fails I just show toast with message "Failed to sign-in".

**Comment by Salladin95** [comment]
Got it. I guess it's done than, I'll create PR as soon as I get home

**Comment by topboyasante** [comment]
thanks a lot!

**Comment by Salladin95** [comment]
I made a PR, can you review it?

**Comment by topboyasante** [comment]
sure. done. LGTM!
