### ISSUE TITLE
Implement Sign Out functionality

### ISSUE THREAD

**Issue by topboyasante** [OpenSource-GH/dumsor-tracker-frontend#33]
- Implement sign out functionality. the route to the backend is : `api.dumsor.xyz/api/v1/users/logout`.

**Comment by garrettmroberts** [comment]
Is this issue still open? I'd love to take a crack at it.

**Comment by topboyasante** [comment]
still open @garrettmroberts. all the best!

**Comment by garrettmroberts** [comment]
@topboyasante  Is the login issue mentioned on issue #32 still unaddressed?

**Comment by topboyasante** [comment]
i think it's being taken care of by Khalid @Salladin95
